name: Documentation Checker

# TRIGGER: Uruchomienie przy wypchnięciu zmian
on: [push]

# JOBS: Definicja zadań
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      # Krok 1: Pobranie kodu źródłowego
      - name: Checkout code
        uses: actions/checkout@v3

      # Krok 2: Uruchomienie walidatora linków
      - name: Check links in README
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  # ZADANIE 2: Sprawdzanie składni (NOWOŚĆ)
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Markdown Lint
        # Używamy gotowego lintera
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

      # NOWY KROK: Generowanie raportu
      - name: Utworz Raport
        if: always() # Wykonaj nawet jak linter znajdzie błędy
        run: echo "Analiza składni zakończona sukcesem dla commitu $(git rev-parse --short HEAD)" > raport-jakosci.txt

      # NOWY KROK: Wysyłanie artefaktu
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raport-audytu
          path: raport-jakosci.txt
